NP-32361-move-scopus-generate, copied
BIBSYSDEV/nva-publication-api pull request #1011
Opened 2023-01-31 11:17 UTC by truhacevkir

Copied scopus-generate to publication-api repo

2023-01-31 14:30 UTC, anetteOlli requested changes

2023-01-31 14:30 UTC, anetteOlli commented on scopus-generate/src/main/resources/xocs-ani515.xjb
> +<bindings xmlns="https://jakarta.ee/xml/ns/jaxb"
Du mangler en hel fil. build.gradle i scopus-generate.

Tips: hvis du bygger scopus-generate så skal du få en haug med auto-genererte klasser i build mappa. build/generated/xjc/

2023-01-31 14:31 UTC, anetteOlli commented on scopus-generate/src/main/resources/xocs-ani515.xjb
> +<bindings xmlns="https://jakarta.ee/xml/ns/jaxb"
![image](https://user-images.githubusercontent.com/44363838/215788502-9e8cc5b3-f291-4aa9-a688-d054a23b44bd.png)

2023-01-31 14:34 UTC, anetteOlli commented on gradle/libs.versions.toml
> +
hmm, det høres rart ut at xsd2java-jakarta har versjon 3.0.1 mens resten har 3.0.2. Det kan være at det må være sånn, men gjerne dobbeltsjekk

2023-01-31 15:05 UTC, truhacevkir commented on scopus-generate/src/main/resources/xocs-ani515.xjb
> +<bindings xmlns="https://jakarta.ee/xml/ns/jaxb"
fikset

2023-02-01 07:25 UTC, truhacevkir commented on gradle/libs.versions.toml
> +
Bygger ikke med en annen versjon

2023-02-01 08:10 UTC, merged