Np 2892 cristin import grants conversion
BIBSYSDEV/nva-publication-api pull request #1044
Opened 2023-02-16 14:49 UTC by anetteOlli

2023-02-20 09:30 UTC, truhacevkir approved these changes

2023-02-22 07:54 UTC, ketilaa requested changes

2023-02-22 12:45 UTC, anetteOlli commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinGrant.java
> +                   .addChild(sourceCode.toLowerCase(Locale.ROOT))
fikset.

2023-02-22 12:45 UTC, anetteOlli commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinMapper.java
> +    private List<Funding> maptoNvaFunding(List<CristinGrant> grants) {
fikset

2023-02-22 12:45 UTC, anetteOlli commented on cristin-import/src/test/java/cucumber/GeneralMappingRules.java
> +    public void ztheNvaResourceHasACreationDateEqualTo(String expectedIsoInstant) {
fikset

2023-02-22 14:07 UTC, merged