Np 42020 create published as external
BIBSYSDEV/nva-publication-api pull request #1101
Opened 2023-03-29 18:55 UTC by sondrev

2023-03-29 18:56 UTC, sondrev commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/ResourceService.java
> +    public static final String NOT_PUBLISHABLE = "Publication is not publiashable. Check main title and doi";
typo in publiashable

2023-03-29 19:00 UTC, sondrev commented on publication-commons/src/main/java/no/unit/nva/publication/RequestUtil.java
> +        return UserInstance.createMachineUser(resourceOwner, client.getCustomerUri());
machineUser->externalClient
Forgot to refactor this

2023-03-30 07:34 UTC, brinxmat requested changes

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/create/CreatePublicationHandlerTest.java
> +        InputStream inputStream = createPublicationRequest(request);
var

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/create/CreatePublicationHandlerTest.java
> +        InputStream inputStream = requestFromExternalClient(request);
var

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/create/CreatePublicationHandlerTest.java
> +        InputStream inputStream = requestFromExternalClient(request);
var

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/create/CreatePublicationHandlerTest.java
> +    void requestToHandlerWithStatusPublishedFromAnRegularUserShouldPersistDocumentAsDraft() throws Exception {
shouldPersistDraftWhenRegularUserAttemptsToPersistPublicationWithStatusPublished

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/create/CreatePublicationHandlerTest.java
> +    void requestToHandlerWithStatusFromAnExternalClientShouldPersistDocumentWithSameStatus(String statusString)
shouldPersistProvidedStatusWhenMachineUserPersistsPublicationWithAnyStatus

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/delete/DeletePublicationHandlerTest.java
> +    void handleRequestReturnsErrorWhenCallerIsNotOwnerOfPublicationAndCalledIsExternalClient()
shouldReturn

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/delete/DeletePublicationHandlerTest.java
> +    void handleRequestReturnsUnauthorizedWhenCallerIsMissingClientId()
shouldReturn

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/update/UpdatePublicationHandlerTest.java
> +    void handlerUpdatesPublicationWhenInputIsValidAndUserIsExternalClient() throws IOException, BadRequestException {
should…

2023-03-30 07:34 UTC, brinxmat commented on publication-rest/src/test/java/no/unit/nva/publication/update/UpdatePublicationHandlerTest.java
> +    void handlerThrowsNotFoundWhenExternalClientTriesToUpdateResourcesCreatedByOthers()
should

2023-03-30 10:12 UTC, merged