Np 44561 create endpoint for updating ticket assignee
BIBSYSDEV/nva-publication-api pull request #1135
Opened 2023-04-21 06:42 UTC by EyobSikt

Creating endpoint (PUT) for updating ticket assignee.

2023-04-24 07:38 UTC, anetteOlli commented on tickets/src/main/java/no/unit/nva/publication/ticket/update/updateTicketAssigneeHandler.java
> +        createFindableDoiAndPersistDoiOnPublication(publication);
Shouldn't the ticket get status "complete" if the publication has a findable DOI?

2023-04-24 07:44 UTC, anetteOlli requested changes

2023-04-24 07:44 UTC, anetteOlli commented on tickets/src/main/java/no/unit/nva/publication/ticket/update/updateTicketAssigneeHandler.java
> +        throws NotFoundException, BadMethodException, BadGatewayException {
From the open-api spec it seems to me that you submit a ticket with an assigne to update the database with. But from the code the assigne is fetched from the request info?

If the correct version is from request info, the open-api spec should not receive a body.

And if the body should be used so you can assign whoever you want, the findableDoiTicketSideEffects is a bit sketchy.

2023-04-24 08:54 UTC, anetteOlli commented on docs/openapi.yaml
> +              $ref: '#/components/schemas/Ticket'
schema: {}

2023-04-24 13:43 UTC, truhacevkir requested changes

2023-04-24 13:43 UTC, truhacevkir commented on tickets/src/main/java/no/unit/nva/publication/ticket/update/updateTicketAssigneeHandler.java
> +        }
Not sure if you have to include doi side effects here. When updating status for pubishingRequest, we have side effects to make doi findable/delete it. In your case you are adding assignee, that should not do anything with doi (as I see it)

2023-04-24 13:43 UTC, truhacevkir commented on tickets/src/test/java/no/unit/nva/publication/ticket/update/updateTicketAssigneeHandlerTest.java
> +    }
Not sure if you have to test this, as your handler has nothing to do with DOI

2023-04-25 06:29 UTC, truhacevkir commented
Do we want to update ticket assignee for COMPLETED ticket?

2023-04-25 06:32 UTC, truhacevkir commented on tickets/src/main/java/no/unit/nva/publication/ticket/update/updateTicketAssigneeHandler.java
Class name has to start with capital letter

2023-04-25 06:33 UTC, truhacevkir commented on tickets/src/test/java/no/unit/nva/publication/ticket/update/updateTicketAssigneeHandlerTest.java
> +            .withCustomerId(customer)
.withCustomerId() is deprecated, you can use withCurrentCustomer() instead

2023-04-26 08:38 UTC, anetteOlli commented on docs/openapi.yaml
> +              $ref: '#/components/schemas/Ticket'
This comment is no longer valid.

2023-05-02 11:59 UTC, closed without merging