Np 44691 import candidate
BIBSYSDEV/nva-publication-api pull request #1175
Opened 2023-05-09 07:14 UTC by truhacevkir

2023-05-10 08:26 UTC, anetteOlli requested changes

2023-05-10 08:26 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/model/business/ImportCandidate.java
> +    public static final class Builder {
Or you could to a builder with two properties: publication and importStatus.

2023-05-10 08:26 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/model/business/ImportCandidate.java
> +    public static final class Builder {
Also should we be nasty and say that if the object doesn't have an importStatus it is not an ImportCandidate?


You can do that in the build method or the constructor: throw an exception if importStatus is null.

2023-05-10 10:59 UTC, truhacevkir commented on template.yaml
> -  # NB! for compatibility reasons (ResourceService is re-used) NvaImportCandidatesTable should be a copy of NvaResourcesTable
Det var ikke mening :)

2023-05-11 07:23 UTC, anetteOlli approved these changes

2023-05-11 12:05 UTC, merged