Code cleanup in expansion test
BIBSYSDEV/nva-publication-api pull request #1227
Opened 2023-06-06 11:01 UTC by monaullah

Code cleanup in test for correct number of contributors after expansion of publication with same person in different contribution roles.

2023-06-08 07:51 UTC, brinxmat requested changes

2023-06-08 07:51 UTC, brinxmat commented on expansion/src/test/java/no/unit/nva/expansion/ResourceExpansionServiceTest.java
> +                   .filter(contributor -> contributor.getIdentity().getId().equals(id))
Call to chained gets should be. extracted to a named method,  and the NPE problems should be managed :)

2023-06-08 07:51 UTC, brinxmat commented on expansion/src/test/java/no/unit/nva/expansion/ResourceExpansionServiceTest.java
> +        contributors.add(actor);
There is an abstraction missing here :)

2023-06-08 11:59 UTC, monaullah commented on expansion/src/test/java/no/unit/nva/expansion/ResourceExpansionServiceTest.java
> +        contributors.add(actor);
Whoops, fixed new commit

2023-06-09 08:26 UTC, anetteOlli approved these changes

2023-06-11 13:53 UTC, brinxmat approved these changes

2023-06-12 07:12 UTC, merged