NP-45320-cristin-import-latest-s3-uri-in-error-reports
BIBSYSDEV/nva-publication-api pull request #1315
Opened 2023-09-25 13:50 UTC by anetteOlli

2023-09-25 13:59 UTC, anetteOlli commented
There's pros and cons for this PR.

We need an easy method for re-importing single cristin-result that fails because of  some IOexception.

The cons of this is that we now need to be very-careful and move/delete everything in the error path before running a new import-job, otherwise we will just overwrite the previous error reports.

2023-09-26 07:30 UTC, brinxmat requested changes

2023-09-26 07:30 UTC, brinxmat commented on cristin-import/src/test/java/no/unit/nva/cristin/lambda/CristinEntryEventConsumerTest.java
> +    private SQSEvent createSQSevent(FileContentsEvent eventBody) throws IOException {
`createSqsEvent` to avoid checkstyle complaints

2023-09-26 07:38 UTC, torarnet approved these changes

2023-09-26 12:42 UTC, brinxmat approved these changes

2023-09-26 13:12 UTC, merged