Refactoring
BIBSYSDEV/nva-publication-api pull request #135
Opened 2021-01-08 10:38 UTC by axthosarouris

2021-01-08 17:27 UTC, axthosarouris commented on create-publication/src/main/java/no/unit/nva/publication/create/CreateResourceHandler.java
> +package no.unit.nva.publication.create;
Do not review this class. It is a toy class to verify that things were actually written in Dynamo

2021-01-08 17:28 UTC, axthosarouris commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/DynamoDBPublicationService.java
> +@SuppressWarnings("PMD.GodClass")
PMD complained

2021-01-11 16:47 UTC, axthosarouris commented on build.gradle
> +        awsSdkVersion = '1.11.871'
temporary downgrade because I has issues with the client. Will look into it.

2021-01-11 16:48 UTC, axthosarouris commented on build.gradle
> +                    minimum = 0.00
Will be put to 1 after SortableIdentrifier is moved to commons.

2021-01-11 16:48 UTC, axthosarouris commented on config/checkstyle/checkstyle.xml
> -    <module name="MissingJavadocMethod">
To avoid noisy comments that do not add any information

2021-01-11 16:51 UTC, axthosarouris commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/DynamoDBPublicationService.java
> +import static java.util.Objects.isNull;
All  changes, except for the "God Class" are only automatic reformating

2021-01-11 16:53 UTC, axthosarouris commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/ResourceService.java
> +        return String.format("%s = %s AND %s = %s",
the condition is "#partitionKey = :partitionKey AND #sortKey = :sortKey"

2021-01-11 16:55 UTC, axthosarouris commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/ResourceServiceUtils.java
> +        return String.format("attribute_not_exists(%s) AND attribute_not_exists(%s)",
condition is " attribute_not_exists(PK0) and attribute_not_exists(SK0)"

2021-01-11 16:56 UTC, axthosarouris commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/ResourceServiceUtils.java
> +            PARTITION_KEY_NAME_PLACEHOLDER, PRIMARY_KEY_PARTITION_KEY_NAME,
The Map is 

```
 #partitionKey -> PK0, #sortKey->SK0
```

2021-01-11 16:57 UTC, axthosarouris commented on publication-commons/src/test/java/no/unit/nva/publication/service/impl/DynamoDBPublicationServiceTest.java
> +    //DONE
Functionality that has been implemented so far

2021-01-11 16:58 UTC, axthosarouris commented on publication-testing/src/main/java/no/unit/nva/publication/service/ResourcesDynamoDbLocalTest.java
> +public class ResourcesDynamoDbLocalTest {
Set up The local dynamo with for the functionality so far. Not all GSIs are included yet

2021-01-11 16:59 UTC, axthosarouris commented on storage-model/src/main/java/no/unit/nva/publication/identifiers/SortableIdentifier.java
> +@JsonSerialize(using = SortableIdentifierSerializer.class)
Sortable identifier that serializes as String and Deserializes from String.

2021-01-12 10:26 UTC, brinxmat requested changes

2021-01-12 10:26 UTC, brinxmat commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/ResourceService.java
> +        return Map.of(PARTITION_KEY_VALUE_PLACEHOLDER,
Probably put the placeholders directly into the substitution template as this makes the template more readable, then extract the substitution template to a named constant

2021-01-12 10:26 UTC, brinxmat commented on storage-model/src/main/java/no/unit/nva/publication/identifiers/SortableIdentifierSerializer.java
> +            throw new RuntimeException(SERIALIZATION_EXCEPTION_ERROR + " " + printIdentifierValue(value));
Do we dislike trailing spaces in constants?

2021-01-13 13:43 UTC, janbj approved these changes

2021-01-13 13:43 UTC, janbj commented on template.yaml
> +            TableName: OrestisResources
To be changed before merge?

2021-01-14 09:39 UTC, brinxmat approved these changes

2021-01-15 09:48 UTC, merged