Np 45593 extract file from doi
BIBSYSDEV/nva-publication-api pull request #1370
Opened 2023-11-06 11:48 UTC by truhacevkir

2023-11-07 14:21 UTC, brinxmat requested changes

2023-11-07 14:21 UTC, brinxmat commented on scopus-import/src/main/java/no/sikt/nva/scopus/conversion/files/ScopusFileConverter.java
> +    }
These look like they belong to License.

2023-11-07 14:21 UTC, brinxmat commented on scopus-import/src/main/java/no/sikt/nva/scopus/conversion/files/ScopusFileConverter.java
> +                   .filter(l -> l.getContentVersion().equals(crossrefLink.getContentVersion()))
l?

2023-11-07 14:21 UTC, brinxmat commented on scopus-import/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +    void some() {
Some?

2023-11-08 14:19 UTC, anetteOlli approved these changes

2023-11-08 14:34 UTC, merged