Np 45600 phisycally delete publication
BIBSYSDEV/nva-publication-api pull request #1437
Opened 2023-12-06 12:20 UTC by truhacevkir

Hard deleted publication can be fetched in the same way as soft deleted, etc. tobmstone/redirect in return.
Keeping only entityDescription and doi of hard deleted publication.
Not removing files from s3 bucket for now.

2023-12-06 13:00 UTC, brinxmat requested changes

2023-12-06 13:33 UTC, truhacevkir commented on buildSrc/src/main/groovy/nva.publication.api.rootplugin.gradle
> +    mavenLocal()
removed

2023-12-06 13:33 UTC, truhacevkir commented on buildSrc/src/main/groovy/nva.publication.api.java-conventions.gradle
> +    mavenLocal()
removed

2023-12-06 14:08 UTC, brinxmat approved these changes

2023-12-06 14:24 UTC, merged

2023-12-11 21:24 UTC, joachimjorgensen commented on publication-rest/src/main/java/no/unit/nva/publication/delete/DeletePublicationHandler.java
> +        if (isEditor(requestInfo, publication) || canEditOwnInstitutionResources(requestInfo)) {
A Curator shouldn't be allowed to hard delete a publication, if I recall correctly?

2023-12-11 21:28 UTC, joachimjorgensen commented on publication-rest/src/test/java/no/unit/nva/publication/delete/DeletePublicationHandlerTest.java
> +                                           publisherUri, EDIT_OWN_INSTITUTION_RESOURCES);
EDIT_OWN_INSTITUTION_RESOURCES is used to define a Curator, not an Editor.