persisting nvi report when nvi reported cristin object
BIBSYSDEV/nva-publication-api pull request #1475
Opened 2024-01-11 07:21 UTC by truhacevkir

2024-01-12 11:41 UTC, anetteOlli requested changes

2024-01-12 11:41 UTC, anetteOlli commented on cristin-import/src/main/java/no/unit/nva/cristin/lambda/CristinEntryEventConsumer.java
> +    private void persistNviReportIfNeeded(PublicationRepresentations publicationRepresentations) {
Beyond the persistNviReportNeeded methods should be in it's own class.

2024-01-12 11:41 UTC, anetteOlli commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinLocale.java
> +
You could make a method toNVIReportFormat here.

2024-01-12 11:41 UTC, anetteOlli commented on cristin-import/src/test/java/no/unit/nva/cristin/lambda/CristinEntryEventConsumerTest.java
> +        assertDoesNotThrow(() -> s3Driver.getFile(expectedFileLocation));
This is a bit on the thin side. I would like some asserts that you can parse the data from the report and that the data contains what you except.

2024-01-22 09:06 UTC, anetteOlli requested changes

2024-01-22 09:06 UTC, anetteOlli commented on scopus-import/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +        @org.intellij.lang.annotations.Language("json")
Dette bør leses fra en fil.

2024-01-22 09:06 UTC, anetteOlli commented on scopus-import/src/test/resources/2-s2.0-85178336140.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Brukes denne? i så fall gi den et navn som dokumenterer hva den tester.

2024-01-22 09:09 UTC, truhacevkir commented on scopus-import/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +        @org.intellij.lang.annotations.Language("json")
fjernet

2024-01-22 09:09 UTC, truhacevkir commented on scopus-import/src/test/resources/2-s2.0-85178336140.xml
> +<?xml version="1.0" encoding="UTF-8"?>
fjernet

2024-01-22 13:08 UTC, anetteOlli approved these changes

2024-01-22 14:05 UTC, merged