refactor(PermissionStrategy): extract CuratingInstitutionsUtil #NP-46339
BIBSYSDEV/nva-publication-api pull request #1573
Opened 2024-03-05 13:23 UTC by torbjokv

2024-03-05 13:29 UTC, torbjokv commented on publication-commons/src/main/java/no/unit/nva/publication/permission/strategy/grant/CuratorPermissionStrategy.java
> -        var resourceOwnerTopLevel = getTopLevelOrgUri(uriRetriever,
removed getTopLevelOrgUri lookup here. had a look at resourceOwner on both a imported and a newly created resource and it looks like its top level every time

2024-03-06 09:55 UTC, brinxmat requested changes

2024-03-06 09:55 UTC, brinxmat commented on publication-commons/src/main/java/no/unit/nva/publication/model/utils/CuratingInstitutionsUtil.java
> +        return contributor.getIdentity() != null && contributor.getIdentity().getId() != null;
Can you Objects::notNull both of these?

2024-03-06 15:18 UTC, brinxmat approved these changes

2024-03-07 08:53 UTC, merged