swap-publisherAuthority-with-publisher-version
BIBSYSDEV/nva-publication-api pull request #1592
Opened 2024-03-14 13:16 UTC by anetteOlli

2024-03-14 13:19 UTC, anetteOlli commented on brage-import/src/test/java/no/sikt/nva/brage/migration/lambda/BrageEntryEventConsumerTest.java
> +                       samePropertyValuesAs(expectedPublication.getAssociatedArtifacts(), "publishedDate"));
Dette fikser de tilfeldige bygg feilene i brage-migrering.

Når en publishedFile blir lagd så settes publishedDate til Instant.now().

2024-03-14 13:57 UTC, anetteOlli commented on scopus-import/src/main/java/no/sikt/nva/scopus/conversion/files/ScopusFileConverter.java
> +    private PublisherVersion determinePublisherVersion(CrossrefLink crossrefLink) {
I had no idea what those enums meant when I started with this, but I also found some documentation: https://www.crossref.org/schema/crossref_output3.0.1.xsd

2024-03-14 14:02 UTC, ketilaa approved these changes

2024-03-15 11:55 UTC, brinxmat requested changes
Small changes

2024-03-18 12:41 UTC, brinxmat approved these changes

2024-03-20 08:42 UTC, merged