Np 46622 rerun failed cristin objects
BIBSYSDEV/nva-publication-api pull request #1631
Opened 2024-04-24 06:47 UTC by truhacevkir

2024-04-24 08:39 UTC, truhacevkir commented on cristin-import/src/test/java/no/unit/nva/cristin/FakeAmazonSQS.java
> +public class FakeAmazonSQS implements AmazonSQS {
Had to copy this over here.

2024-04-26 07:55 UTC, anetteOlli commented on template.yaml
> +              - !Sub 'arn:aws:s3:::cristin-import-${AWS::AccountId}/*'
Supert, at du ikke gikk for stjerne.

2024-04-26 08:01 UTC, anetteOlli requested changes

2024-04-26 08:01 UTC, anetteOlli commented on cristin-import/src/main/java/no/unit/nva/cristin/lambda/CristinRerunErrorsEventEmitter.java
> +        this.batchMessenger = new SqsBatchMessenger(defaultAmazonSQS(), CRISTIN_ENTRY_QUEUE);
use this(new S3Driver(S3Driver.defaultS3Client().build(), CRISTIN_IMPORT_BUCKET), new SqsBatchMessenger(defaultAmazonSQS(), CRISTIN_ENTRY_QUEUE)) instead, that way the default constructor stays in sync with the parameterised constructor.

2024-04-26 08:01 UTC, anetteOlli commented on cristin-import/src/main/java/no/unit/nva/cristin/lambda/CristinRerunErrorsEventEmitter.java
> +        var batchResult = putMessagesOnQueue(errorReports);
Doesn't the batchResult contains information regarding failed events?

Maybe not delete those from s3?

2024-04-26 08:02 UTC, truhacevkir commented on cristin-import/src/main/java/no/unit/nva/cristin/lambda/RerunFailedEntriesEvent.java
> +        return UriWrapper.fromUri(uri).getPath().removeRoot();
Ja, har testet, men den returnerer uri med slash foran og liker ikke s3Driver.listFiles funksjonen, så jeg gikk for den varianten her.

2024-04-26 09:07 UTC, anetteOlli approved these changes

2024-04-26 09:14 UTC, merged