NP-46786 Add finalizedBy to DTOs for DoiRequest and PublishingRequest
BIBSYSDEV/nva-publication-api pull request #1663
Opened 2024-05-21 10:39 UTC by joachimjorgensen

2024-05-21 11:17 UTC, monaullah requested changes
Verify with test in `GetTicketHandlerTest`? `shouldReturnFinalizedTicket`?

2024-05-21 11:59 UTC, truhacevkir approved these changes

2024-05-22 12:40 UTC, truhacevkir commented on tickets/src/test/java/no/unit/nva/publication/ticket/TicketDtoTest.java
> +    void shouldSerializeAllFieldsWhenConvertingToTicketDto(Class<? extends TicketEntry> ticketType) throws ApiGatewayException {
nice!

2024-05-22 13:26 UTC, monaullah approved these changes

2024-05-22 13:34 UTC, merged