Np 47010 resource service assume eventual consistency will happen
BIBSYSDEV/nva-publication-api pull request #1715
Opened 2024-06-13 14:50 UTC by anetteOlli

2024-06-13 14:51 UTC, anetteOlli commented on brage-import/src/test/java/no/sikt/nva/brage/migration/lambda/BrageEntryEventConsumerTest.java
> -    private Publication persistPublicationWithHandleInAdditionalIdentifiers(String cristinIdentifier, String year,
removed unused method

2024-06-13 14:51 UTC, anetteOlli commented on brage-import/src/test/java/no/sikt/nva/brage/migration/lambda/BrageEntryEventConsumerTest.java
> -        var set = existingPublication.getAdditionalIdentifiers();
apparently roundtripping a publication via Jackson returns a mutable set.

2024-06-13 14:52 UTC, anetteOlli commented on brage-import/src/test/java/no/sikt/nva/brage/migration/testutils/ReferenceGenerator.java
> -                        new VisualArts(VisualArtsSubtype.createOther(null), null, null))
round tripping via Jackson gives you null value, but not you get empty sets or list

2024-06-13 14:52 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/exception/DynamoDBException.java
> -public class DynamoDBException extends ApiGatewayException {
unused class except for inside tests

2024-06-13 14:53 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/exception/ErrorResponseException.java
> -public class ErrorResponseException extends ApiGatewayException {
unused class except for inside tests

2024-06-13 14:53 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/exception/InternalErrorException.java
> -public class InternalErrorException extends ApiGatewayException {
unused class except for inside tests

2024-06-13 14:53 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/exception/NoResponseException.java
> -public class NoResponseException extends ApiGatewayException {
unused class except for inside tests

2024-06-13 14:53 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/exception/NotImplementedException.java
> -public class NotImplementedException extends ApiGatewayException {
unused class except for inside tests

2024-06-13 14:53 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/model/storage/DynamoEntry.java
> -    boolean NO_WRAP = true;
unused constant

2024-06-13 14:53 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/ResourceService.java
> -    public static final String INVALID_PATH_ERROR = "The document path provided in the update expression is invalid "
unused constant

2024-06-13 14:54 UTC, anetteOlli commented on publication-commons/src/main/java/no/unit/nva/publication/service/impl/ServiceWithTransactions.java
> -    public static final String DOUBLE_QUOTES = "\"";
unused constants

2024-06-13 14:54 UTC, anetteOlli commented on publication-commons/src/test/java/no/unit/nva/publication/exception/DynamoDBExceptionTest.java
> -public class DynamoDBExceptionTest {
Unused exception

2024-06-13 15:04 UTC, anetteOlli commented on publication-commons/src/test/java/no/unit/nva/publication/service/impl/ResourceServiceTest.java
> -    void createPublicationReturnsNullWhenResourceDoesNotBecomeAvailable() throws BadRequestException {
Test no longer applicable.

2024-06-13 15:07 UTC, anetteOlli commented
Så forsvant ikke polling metoden 100 %. TicketService kaster exception når den ikke oppnår eventual consistency selv, så jeg lurer på om jeg skal endre der eller ikke. Men kan uansett starte med dette.

2024-06-13 17:40 UTC, brinxmat requested changes
A couple of minor changes, nice job

2024-06-13 17:40 UTC, brinxmat commented on brage-import/src/test/java/no/sikt/nva/brage/migration/testutils/ReferenceGenerator.java
> +                        new VisualArts(VisualArtsSubtype.createOther(null), null, Set.of()))
I'd prefer `Collections.emptySet()` as it looks deliberate

2024-06-13 17:40 UTC, brinxmat commented on brage-import/src/test/java/no/sikt/nva/brage/migration/testutils/ReferenceGenerator.java
> +                    new LiteraryArts(LiteraryArtsSubtypeOther.createOther(null), List.of(), null))
Similarly, `Collections.emptyList()`

2024-06-14 09:29 UTC, brinxmat approved these changes

2024-06-14 10:13 UTC, merged