Np 47377 fixing migrated licenses
BIBSYSDEV/nva-publication-api pull request #1793
Opened 2024-08-26 12:46 UTC by truhacevkir

Adding support for updating licenses for publications.

2024-08-26 12:51 UTC, truhacevkir commented on publication-model/src/main/java/no/unit/nva/model/associatedartifacts/file/File.java
> +        }
I think this builder is a more convenient to use when you consume file without knowing its actual type.

2024-08-27 03:09 UTC, brinxmat requested changes

2024-08-27 03:09 UTC, brinxmat commented on publication-event-handlers/src/test/java/no/unit/nva/publication/events/handlers/batch/UpdatePublicationsInBatchesHandlerTest.java
> +    void shouldThrowIllegalArgumentExceptionWhenUnknownUpdateType() {
This will fail due to the change made to `ManuallyUpdatePublicationUtil.java`, however, validate the creation of the enum object from JSON

2024-08-27 07:40 UTC, truhacevkir commented on publication-event-handlers/src/main/java/no/unit/nva/publication/events/handlers/batch/ManuallyUpdatePublicationUtil.java
> +                   .map(Publisher.class::cast)
Changing similar method in test so they are not identical.

2024-08-28 04:03 UTC, brinxmat approved these changes

2024-08-28 06:08 UTC, merged