add expansion for promoted controbutors & count
BIBSYSDEV/nva-publication-api pull request #1858
Opened 2024-10-03 10:56 UTC by sondrev

2024-10-03 12:41 UTC, truhacevkir approved these changes

2024-10-03 12:41 UTC, truhacevkir commented on expansion/src/main/java/no/unit/nva/expansion/model/ExpandedResource.java
> +        }
maybe split it to multiple methods

2024-10-08 09:28 UTC, monaullah requested changes

2024-10-08 09:28 UTC, monaullah commented on expansion/src/main/java/no/unit/nva/expansion/model/ExpandedResource.java
> +                List<JsonNode> contributorsList = new ArrayList<>();
var

2024-10-08 09:28 UTC, monaullah commented on expansion/src/main/java/no/unit/nva/expansion/model/ExpandedResource.java
> +                ArrayNode arrayNode = new ArrayNode(JsonNodeFactory.instance);
var

2024-10-08 09:28 UTC, monaullah commented on expansion/src/main/java/no/unit/nva/expansion/model/ExpandedResource.java
> +                entityDescription.put(CONTRIBUTORS_PREVIEW, arrayNode);
`put` is deprecated, use `entityDescription.set(CONTRIBUTORS_PREVIEW, arrayNode);`

2024-10-08 09:28 UTC, monaullah commented on expansion/src/main/java/no/unit/nva/expansion/model/ExpandedResource.java
> +                                             .sorted(Comparator.comparingInt(c -> c.get(CONTRIBUTOR_SEQUENCE).asInt()))
rename `c` to `contributor`?

2024-10-08 09:28 UTC, monaullah commented on expansion/src/main/java/no/unit/nva/expansion/model/ExpandedResource.java
> +    private static void injectContributorsPreview(ObjectNode json) {
This is quite a big method, refactor and extract to method to make more readable? Suggestion:

```
private static void injectContributorsPreview(ObjectNode json) {
        var contributors = json.at(CONTRIBUTORS_PTR);
        if (!contributors.isMissingNode() && contributors.isArray()) {
            var entityDescription = (ObjectNode) json.at(ENTITY_DESCRIPTION_PTR);
            if (!entityDescription.isMissingNode() && entityDescription.isObject()) {
                var sortedContributors = sortBySequenceAndVerificationLimitTen(contributors);
                var sortedContributorsArrayNode = new ArrayNode(JsonNodeFactory.instance).addAll(sortedContributors);

                entityDescription.set(CONTRIBUTORS_PREVIEW, sortedContributorsArrayNode);
            }
        }
    }

    private static List<JsonNode> sortBySequenceAndVerificationLimitTen(JsonNode contributors) {
        var contributorsList = new ArrayList<JsonNode>();
        contributors.forEach(contributorsList::add);
        return contributorsList.stream()
                   .sorted(Comparator.comparingInt(contributor -> contributor.get(CONTRIBUTOR_SEQUENCE).asInt()))
                   .sorted(ExpandedResource::sortContributorByVerifiedFirst)
                   .limit(MAX_CONTRIBUTORS_PREVIEW).toList();
    }
```

2024-10-08 09:28 UTC, monaullah commented on expansion/src/test/java/no/unit/nva/publication/indexing/ExpandedResourceTest.java
> +    void shouldReturnIndexDocumentWithContributorsPreviewAndCount() throws Exception {
Test limit? Test data setup with more than 10 contributors?

2024-10-08 09:53 UTC, brinxmat approved these changes
Approving to move on, but see other reviewer's comments

2024-10-08 11:05 UTC, merged