Np 48181 model for log entry
BIBSYSDEV/nva-publication-api pull request #1958
Opened 2024-12-03 12:10 UTC by truhacevkir

Creating model for log entry which will be persisted to database and served to frontend.

2024-12-03 12:11 UTC, truhacevkir commented on publication-commons/src/main/java/no/unit/nva/publication/model/business/logentry/LogEntry.java
> +public record LogEntry(LogTopic topic, Instant timestamp, User performedBy) {
Come with suggestions to naming here.

2024-12-04 08:04 UTC, brinxmat requested changes

2024-12-04 08:04 UTC, brinxmat commented on publication-commons/src/main/java/no/unit/nva/publication/model/business/logentry/LogTopic.java
> +        "FileUploaded"), FILE_PUBLISHED("FilePublished"), FILE_REJECTED("FileRejected");
Put these each on their own line and sort alphabetically

2024-12-04 08:04 UTC, brinxmat commented on publication-commons/src/test/java/no/unit/nva/publication/model/business/logentry/LogEntryTest.java
> +        var logEntry = randomLogEntry(SortableIdentifier.next());
Probably not a random, but a parameterised test.

2024-12-04 08:05 UTC, torbjokv approved these changes

2024-12-04 08:50 UTC, merged