Break doi update infinite loop
BIBSYSDEV/nva-publication-api pull request #219
Opened 2021-02-25 10:51 UTC by axthosarouris

2021-02-28 19:05 UTC, axthosarouris commented on publication-event-dtopublicationdoi-producer/src/test/java/no/unit/nva/doi/event/producer/DynamoDbFanoutPublicationDtoProducerTest.java
> +    void handlerCreatesNoOutputWhenPublicationUpdateDiffersOnlyInModifiedDate() throws JsonProcessingException {
this is the most important test

2021-03-01 04:34 UTC, brinxmat requested changes

2021-03-01 04:34 UTC, brinxmat commented on publication-doi-commons/src/main/java/no/unit/nva/publication/doi/update/dto/DoiRegistrarEntryFields.java
> +    @JacocoGenerated
Move the overridden methods to the bottom of the class.

2021-03-01 04:34 UTC, brinxmat commented on publication-event-dtopublicationdoi-producer/src/main/java/no/unit/nva/doi/event/producer/DynamoDbFanoutPublicationDtoProducer.java
> +        DoiRegistrarEntryFields doiInfoNew = DoiRegistrarEntryFields.fromPublication(newPublication);
We should talk about this, I think we may be overthinking

2021-03-01 04:34 UTC, brinxmat commented on publication-event-dtopublicationdoi-producer/src/test/java/no/unit/nva/doi/event/producer/DynamoDbFanoutPublicationDtoProducerTest.java
> +        assertThatEventsDifferOnlyInModifiedDate(event);
A service shouldn't modify an internal field directly

2021-03-01 11:06 UTC, brinxmat approved these changes

2021-03-01 11:11 UTC, merged