Np 2243 write publications to new table
BIBSYSDEV/nva-publication-api pull request #226
Opened 2021-03-04 20:41 UTC by axthosarouris

2021-03-05 13:30 UTC, axthosarouris commented on create-message/src/test/java/no/unit/nva/publication/messages/create/CreateMessageHandlerTest.java
> +        throws IOException, NotFoundException {
I start thinking that all excpections should be Unchecked exceptions

2021-03-08 08:53 UTC, brinxmat requested changes

2021-03-08 08:53 UTC, brinxmat commented on data-migration/src/main/java/no/unit/nva/publication/migration/DataMigration.java
> +
Annotate with @SafeVarargs, I believe this holds in this case

2021-03-08 09:11 UTC, brinxmat reviewed
As I understand, the update is not transactional, given that DynamoDB has a restriction that up-to ten Items may be updated in one transaction, this becomes problematic. Nevertheless, I suggest avoiding partial import of data, so perhaps check that the full import has succeeded before progressing, or remove the partials and add to report.

2021-03-08 09:44 UTC, brinxmat approved these changes

2021-03-08 10:00 UTC, janbj approved these changes

2021-03-08 10:14 UTC, merged