Np 2675 group errors of emitting events by exception name
BIBSYSDEV/nva-publication-api pull request #427
Opened 2021-06-14 13:23 UTC by Eirik-Eide-Saur

2021-06-14 14:37 UTC, brinxmat requested changes

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +    private String removeLastPartOfPath(String path) {
is this removeLastPathSegment?

As far as I can tell, "Segment" is the most commonly used term for host/segment/segment/ where /segment/segment/ is the path

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +        int lastDeliminatorIndex = path.lastIndexOf('/');
lastSegmentStartIndex = path.lastIndexOf(PATH_SEPARATOR)

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +        int lastDeliminatorIndex = path.lastIndexOf('/');
Same as above

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +    private String makeFileEndingError(String filename) {
FileExtension

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +        int lastDot = filename.lastIndexOf('.');
int extensionSeparatorIndex  = …(EXTENSION_SEPARATOR), although "." is only a separator in this sense in the last position…

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +    public static final String ERROR_FILE_ENDING = "error";
Probably FILE_EXTENSION_ERROR

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +        List<PutEventsResult> putEventsResults;
Is there a reason why the variable isn't assigned immediately?

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +                   .addChild(failedEntries.isSuccess() ? "PartialFailure"
PARTIAL_FAILURE, I'm annoying like this ;)

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/main/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitter.java
> +            "File in location: " + s3Location + ". Failed with the following exception: "
psfs  EXCEPTION_STACKTRACE_MESSAGE_TEMPLATE = ""File in location: %s Failed with the following exception:  %s";
String.format(EXCEPTION_STACKTRACE_MESSAGE_TEMPLATE, s3Location, stacktraceInSingleLine(…));

2021-06-14 14:37 UTC, brinxmat commented on s3-import-commons/src/test/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitterTest.java
> +            ERRORS_FOLDER + INPUT_PATH + "/" + exception.getClass().getSimpleName() + ERROR_FILE;
As far as I can tell, this code is in essence repeated so a method like:

```
    constructFileLocation(classNameOrWhateverItIs, file) {
       String.format(LOCATION_TEMPLATE, classNameOrWhateverItIs, file)
    }
```

2021-06-15 10:29 UTC, axthosarouris requested changes

2021-06-15 10:29 UTC, axthosarouris commented on s3-import-commons/src/test/java/no/unit/nva/publication/s3imports/FileEntriesEventEmitterTest.java
> +
This is in general a bit problematic because we include the path separator to the filenames

2021-06-15 18:48 UTC, brinxmat requested changes

2021-06-16 09:20 UTC, brinxmat approved these changes

2021-06-16 09:25 UTC, merged