NP-2926 Map ARTIKKEL, ARTIKKEL_POP og OVERSIKTSART to JOURNAL_ARTICLE
BIBSYSDEV/nva-publication-api pull request #481
Opened 2021-07-26 08:36 UTC by Eirik-Eide-Saur

2021-07-26 08:39 UTC, Eirik-Eide-Saur commented
CHAPTERACADEMIC AND LEXICALIMPORT where both skipped as they are of type CHAPTER. CHAPTERACADEMIC is already mapped.

2021-08-04 10:43 UTC, axthosarouris requested changes

2021-08-04 10:43 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinSecondaryCategory.java
> +    JOURNAL_ARTICLE("ARTIKKEL_FAG", "JOURNAL_ARTICLE", "ARTIKKEL", "ARTIKKEL_POP", "OVERSIKTSART"),
This is our internal mapping of the Cristin categories. I think that we should not compress the cristin categories and do in practice the mapping to the NVA catogory here. It is better to create more categories with names based loosely on the cristin english names and perform the mapping in the CristinMapper, i.e., extend the `isJournal()` method.

2021-08-04 10:43 UTC, axthosarouris commented on cristin-import/src/test/resources/features/JournalArticleRules.feature
> +  Scenario: Map returns a Journal Article NVA Resource when the Cristin Result is an "ARTICLE"
An "Academic Article" maps to a Journal Article. I think it is better if in the scenario titles we use the english name of the cristin category as it appears in the excel file (column VARBEIDUNDERKATNAVN_ENGELSK).

2021-08-04 10:43 UTC, axthosarouris commented on cristin-import/src/test/resources/features/JournalArticleRules.feature
> +    Given a valid Cristin Result with secondary category "ARTIKKEL"
ditto

2021-08-04 10:43 UTC, axthosarouris commented on cristin-import/src/test/resources/features/JournalArticleRules.feature
> +  Scenario: Map returns a Journal Article NVA Resource when the Cristin Result is an "POPULARARTICLE"
ditto

2021-08-04 10:43 UTC, axthosarouris commented on cristin-import/src/test/resources/features/JournalArticleRules.feature
> +  Scenario: Map returns a Journal Article NVA Resource when the Cristin Result is an "ACADEMICREVIEW"
ditto

2021-08-11 12:48 UTC, axthosarouris requested changes

2021-08-11 13:20 UTC, merged