NP-3036 Separate the PublicationInstance building into a class
BIBSYSDEV/nva-publication-api pull request #515
Opened 2021-08-24 08:56 UTC by Eirik-Eide-Saur

2021-08-24 08:58 UTC, Eirik-Eide-Saur commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinMapper.java
> +    public CristinBookOrReportMetadata extractCristinBookReport() {
This and the method extractCristinJournalPublication method are made public as they need to be reach from the new class PublicationInstanceBuilder

2021-08-24 08:59 UTC, Eirik-Eide-Saur commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/PublicationInstanceBuilder.java
> +        this.mapper = new CristinMapper(cristinObject);
Not a big fan of this solution. I do believe all the "extractData" methods should be moved into its own class, but for now this gives access to the methods needed both in this and the CristinMapper class.

2021-08-24 09:38 UTC, axthosarouris requested changes

2021-08-24 09:38 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/PublicationInstanceBuilder.java
> +        return mapper.extractCristinJournalPublication().getPagesBegin();
A Mapper has a PublicationInstanceBuilder which has a Mapper for just getting a field from the CristinObect?

2021-08-24 09:38 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/PublicationInstanceBuilder.java
> +        return mapper.extractCristinJournalPublication().getPagesBegin();
The only reason you are using this method is to handle the case where the cristinObject is null. Require that in the constructor and simplify your code

2021-08-24 12:28 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/PublicationInstanceBuilder.java
> +        Validate.notNull(cristinObject, ERROR_CRISTIN_OBJECT_IS_NULL);
better use Objects.requireNonNull that is native Java. Also the class you are using is not supposed to be used by end-users of the library.

2021-08-24 12:31 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/PublicationInstanceBuilder.java
> +    @SuppressWarnings("PMD.CognitiveComplexity")
If quality check fail, it is an indication that things should be refactored even more, I have created a PR with a suggestion on breaking up this class even more.  Here is the link: https://github.com/BIBSYSDEV/nva-publication-api/pull/516 .

The suggestion is not finished, it has some replication in the exception handling but shows the general direction. If you like my suggestion you can merge my branch to yours and polish it where necessary.

2021-08-24 12:32 UTC, axthosarouris requested changes
based on the comments above

2021-08-24 12:32 UTC, axthosarouris commented on cristin-import/src/test/java/no/unit/nva/cristin/lambda/CristinEntryEventConsumerTest.java
> +        assertThat(cause.getMessage(), is(containsString(PublicationInstanceBuilder.ERROR_PARSING_SECONDARY_CATEGORY)));
"is" is not necessary here.

2021-08-25 10:56 UTC, axthosarouris approved these changes

2021-08-25 10:56 UTC, merged