Np 3099 map fields and categories for chapter
BIBSYSDEV/nva-publication-api pull request #528
Opened 2021-09-13 07:15 UTC by Eirik-Eide-Saur

2021-09-13 07:24 UTC, Eirik-Eide-Saur commented
Daniel, trenger at du tar en titt på det som er oppdatert i ontologi filen. Har satt en til UNKNOWN og trenger en bekreftelse på at de andre antagelsene mine er riktig. Om det er noe som er feil, kom gjerne med forslag så skal jeg innkludere dem.

2021-09-13 11:16 UTC, axthosarouris requested changes

2021-09-13 11:16 UTC, axthosarouris commented on docs/cristin.ttl
> +:TYPE_BOK_RAPPORT_DEL
PR already exists for this part: https://github.com/BIBSYSDEV/nva-publication-api/pull/514. Remove from here and add comments if necessary to that PR

2021-09-13 13:40 UTC, axthosarouris submitted a review, later dismissed

2021-09-15 07:04 UTC, axthosarouris approved these changes

2021-09-15 07:04 UTC, merged