Np 3130 map hrcs codes
BIBSYSDEV/nva-publication-api pull request #545
Opened 2021-09-21 13:26 UTC by Eirik-Eide-Saur

2021-09-22 07:31 UTC, axthosarouris requested changes

2021-09-22 07:31 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinHrcsCategoriesAndActiveties.java
> +        String categoryIdSubtractedByOne = subtractNumericValueOfStringByOne(categoryId);
adjustCategoryIdIndex

2021-09-22 07:31 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinHrcsCategoriesAndActiveties.java
> +        //NVA uses 0-indexing while Cristin starts at 1...
This should be a comment in the method adjustCategoryIndex

2021-09-22 07:31 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinHrcsCategoriesAndActiveties.java
> +        return numberAsString.length() == 1 ? "00" + numberAsString : "0" + numberAsString;
https://stackoverflow.com/questions/6034523/format-an-integer-using-java-string-format

2021-09-22 07:31 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinHrcsCategoriesAndActiveties.java
> +    public static final String HRCS_CATEGORY_URI = "https://nva.unit.no/hrcs/category/";
This is not going to work for any other environment except for production. We have done similar work in the past, use the env variables for the custom domain.

2021-09-22 07:31 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinHrcsCategoriesAndActiveties.java
> +        return HRCS_CATEGORY_URI + categoryIdSubtractedByOneWithLeadingZeroes;
Create the URI here. Why are you returning a String that is a URI and not directly a URI?

2021-09-22 07:31 UTC, axthosarouris commented on cristin-import/src/test/resources/features/GeneralMappingRules.feature
> +      | 13                | 3.1            |
3 digits means that there can be a 3 digit category. How about helsekategorikodes with 3 digits?

2021-09-22 07:52 UTC, axthosarouris requested changes
It seems that not all

2021-09-22 07:52 UTC, axthosarouris commented on cristin-import/src/test/resources/features/GeneralMappingRules.feature
> +  Scenario: The Cristin Result's HRCS values are used to generate the URIs for the NVA Resource
Do we take care of helsekategorikode and aktivitetskode values that have the expected format but they do not exist?

2021-09-23 10:05 UTC, brinxmat requested changes

2021-09-23 10:05 UTC, brinxmat commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinHrcsCategoriesAndActiveties.java
> +    public CristinHrcsCategoriesAndActiveties.CristinHrcsBuilder copy() {
s/Activeties/Activities/ in all occurrences

2021-09-23 10:05 UTC, brinxmat commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinMapper.java
> +        if (extractCristinHrcsCategoriesAndActivities() == null) {
isNull(extractCristinHrcsCategoriesAndActivities()), or return an optional from the method called

2021-09-23 11:06 UTC, axthosarouris commented on cristin-import/src/main/java/no/unit/nva/cristin/mapper/CristinHrcsCategoriesAndActiveties.java
> +        if (activityAsInt < 1 || activityAsInt > 8.5) {
1 and 8.5 should become constants.  But I agree with Rurik, that it makes more sense to treat these values as a small set of valid values that should be probably hardcoded to a Map of CristinValue->NvaValue pairs

2021-09-24 13:50 UTC, axthosarouris approved these changes

2021-09-27 08:08 UTC, brinxmat approved these changes

2021-09-27 08:14 UTC, merged