create AffiliationSelectionService
BIBSYSDEV/nva-publication-api pull request #663
Opened 2021-12-09 13:26 UTC by axthosarouris

2021-12-09 22:46 UTC, brinxmat requested changes

2021-12-09 22:46 UTC, brinxmat commented on publication-commons/src/test/java/no/unit/nva/publication/service/impl/AffiliationSelectionServiceTest.java
> +        URI mostSpecificUnitId = URI.create("https://api.cristin.no/v2/units/194.63.10.0");
Either one or the other, var, probably. Elsewhere too.

2021-12-10 07:53 UTC, janbj commented on publication-commons/src/main/java/no/unit/nva/publication/utils/OrgUnitId.java
> + * selects a random one.
Maybe we should that randomness is not by choice?

2021-12-10 08:02 UTC, janbj commented on publication-commons/src/test/java/no/unit/nva/publication/external/services/PersonApiClientTest.java
> +        assertThat(userAffiliations, is(hasItems(randomOrgUnitId)));
I don't like then name random here, while the value is randomly generated the value is not random within the test.

2021-12-10 09:22 UTC, janbj approved these changes

2021-12-10 09:23 UTC, merged