Added PublicationDtoTestDataGenerator
BIBSYSDEV/nva-publication-api pull request #98
Opened 2020-11-17 09:36 UTC by janbj

2020-11-17 09:37 UTC, axthosarouris approved these changes

2020-11-17 10:48 UTC, axthosarouris approved these changes

2020-11-17 12:08 UTC, norrs requested changes
@janbj The test generator need to return `this` after creation a publication, then you want a method for `as(Doi)Publication(Dto?)` to return the DTOs that were created.

Good idea to also provide a way to clear recorded publications in the test generator.

This so you can access the generated objects that have been created via the test generator.

2020-11-17 13:29 UTC, axthosarouris approved these changes

2020-11-17 13:36 UTC, norrs approved these changes

2020-11-18 11:20 UTC, merged

2020-11-18 16:55 UTC, norrs commented
Acknowledged a bit too fast, I notice this is not what we want. 

The idea with the test generator is we want a recorder of simply adding good and bad objects related to the test that we can retrieve again to do assertions against. 

Idea is that the test generator should do the "complicated" of random generate both valid type of different objects and invalid different type of objects, including test data with different locale etc.